[2023-05-20T14:55:53.623+0000] {processor.py:153} INFO - Started process (PID=32) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:55:53.624+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:55:53.625+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:55:53.624+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:55:53.637+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:55:53.626+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:55:53.638+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:55:53.674+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.067 seconds
[2023-05-20T14:56:23.709+0000] {processor.py:153} INFO - Started process (PID=83) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:23.710+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:56:23.711+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:56:23.711+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:23.713+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:56:23.712+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:56:23.714+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:23.741+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.036 seconds
[2023-05-20T14:56:54.372+0000] {processor.py:153} INFO - Started process (PID=135) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:54.373+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:56:54.373+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:56:54.373+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:54.376+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:56:54.375+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:56:54.376+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:56:54.397+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T14:57:24.966+0000] {processor.py:153} INFO - Started process (PID=187) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:24.967+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:57:24.967+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:57:24.967+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:24.970+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:57:24.969+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:57:24.970+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:24.991+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T14:57:55.250+0000] {processor.py:153} INFO - Started process (PID=239) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:55.251+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:57:55.252+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:57:55.252+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:55.254+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:57:55.253+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:57:55.254+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:57:55.276+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T14:58:25.879+0000] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:25.881+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:58:25.881+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:58:25.881+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:25.884+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:58:25.883+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:58:25.884+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:25.906+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T14:58:56.166+0000] {processor.py:153} INFO - Started process (PID=344) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:56.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:58:56.167+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:58:56.167+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:56.169+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:58:56.168+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:58:56.169+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:58:56.190+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T14:59:26.699+0000] {processor.py:153} INFO - Started process (PID=396) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:26.700+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:59:26.701+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:59:26.701+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:26.703+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:59:26.702+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:59:26.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:26.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.037 seconds
[2023-05-20T14:59:57.017+0000] {processor.py:153} INFO - Started process (PID=448) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:57.025+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T14:59:57.028+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:59:57.026+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:57.031+0000] {logging_mixin.py:137} INFO - [2023-05-20T14:59:57.030+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T14:59:57.031+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T14:59:57.052+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.039 seconds
[2023-05-20T15:00:27.929+0000] {processor.py:153} INFO - Started process (PID=499) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:27.933+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:00:27.933+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:00:27.933+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:27.936+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:00:27.935+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:00:27.936+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:27.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.036 seconds
[2023-05-20T15:00:58.955+0000] {processor.py:153} INFO - Started process (PID=551) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:58.956+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:00:58.956+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:00:58.956+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:58.959+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:00:58.958+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:00:58.959+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:00:58.979+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.027 seconds
[2023-05-20T15:01:29.440+0000] {processor.py:153} INFO - Started process (PID=603) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:29.441+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:01:29.442+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:01:29.441+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:29.444+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:01:29.443+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:01:29.444+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:29.465+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:01:59.913+0000] {processor.py:153} INFO - Started process (PID=655) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:59.914+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:01:59.915+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:01:59.915+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:59.917+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:01:59.916+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:01:59.918+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:01:59.940+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.031 seconds
[2023-05-20T15:02:30.724+0000] {processor.py:153} INFO - Started process (PID=707) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:02:30.725+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:02:30.725+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:02:30.725+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:02:30.728+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:02:30.727+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:02:30.728+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:02:30.749+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:03:01.119+0000] {processor.py:153} INFO - Started process (PID=759) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:01.121+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:03:01.121+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:03:01.121+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:01.124+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:03:01.124+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:03:01.125+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:01.146+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:03:31.829+0000] {processor.py:153} INFO - Started process (PID=811) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:31.830+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:03:31.830+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:03:31.830+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:31.833+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:03:31.832+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:03:31.833+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:03:31.853+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:04:02.279+0000] {processor.py:153} INFO - Started process (PID=863) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:02.280+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:04:02.281+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:04:02.281+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:02.283+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:04:02.282+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:04:02.284+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:02.304+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:04:32.669+0000] {processor.py:153} INFO - Started process (PID=916) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:32.670+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:04:32.670+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:04:32.670+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:32.673+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:04:32.672+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:04:32.673+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:04:32.693+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:05:02.971+0000] {processor.py:153} INFO - Started process (PID=968) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:02.972+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:05:02.973+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:05:02.973+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:02.975+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:05:02.974+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:05:02.976+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:02.997+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:05:33.568+0000] {processor.py:153} INFO - Started process (PID=1020) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:33.570+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:05:33.570+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:05:33.570+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:33.573+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:05:33.572+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:05:33.573+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:05:33.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.035 seconds
[2023-05-20T15:06:04.050+0000] {processor.py:153} INFO - Started process (PID=1072) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:04.051+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:06:04.051+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:06:04.051+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:04.054+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:06:04.053+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:06:04.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:04.076+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:06:34.652+0000] {processor.py:153} INFO - Started process (PID=1124) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:34.653+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:06:34.654+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:06:34.654+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:34.656+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:06:34.655+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:06:34.657+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:06:34.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:07:04.842+0000] {processor.py:153} INFO - Started process (PID=1176) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:04.843+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:07:04.844+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:07:04.844+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:04.846+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:07:04.845+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:07:04.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:04.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:07:35.090+0000] {processor.py:153} INFO - Started process (PID=1228) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:35.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:07:35.092+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:07:35.092+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:35.094+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:07:35.093+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:07:35.094+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:07:35.115+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:08:05.672+0000] {processor.py:153} INFO - Started process (PID=1280) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:05.674+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:08:05.674+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:08:05.674+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:05.677+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:08:05.676+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:08:05.677+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:05.698+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:08:36.511+0000] {processor.py:153} INFO - Started process (PID=1332) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:36.511+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:08:36.512+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:08:36.512+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:36.514+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:08:36.514+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:08:36.515+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:08:36.535+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:09:07.482+0000] {processor.py:153} INFO - Started process (PID=1390) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:07.483+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:09:07.484+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:09:07.484+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:07.486+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:09:07.485+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:09:07.486+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:07.507+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:09:37.921+0000] {processor.py:153} INFO - Started process (PID=1442) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:37.922+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:09:37.922+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:09:37.922+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:37.925+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:09:37.924+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:09:37.925+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:09:37.946+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:10:08.464+0000] {processor.py:153} INFO - Started process (PID=1494) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:10:08.465+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:10:08.466+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:10:08.466+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:10:08.468+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:10:08.468+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:10:08.469+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:10:08.490+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:24:11.962+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:11.968+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:24:11.970+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:24:11.969+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:11.985+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:24:11.972+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:24:11.985+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:12.032+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.079 seconds
[2023-05-20T15:24:42.847+0000] {processor.py:153} INFO - Started process (PID=84) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:42.848+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:24:42.849+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:24:42.849+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:42.851+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:24:42.850+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:24:42.851+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:24:42.872+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:25:13.246+0000] {processor.py:153} INFO - Started process (PID=136) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:13.247+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:25:13.247+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:25:13.247+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:13.250+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:25:13.249+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:25:13.250+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:13.271+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:25:43.752+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:43.761+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:25:43.761+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:25:43.761+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:43.764+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:25:43.763+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:25:43.765+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:25:43.819+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.071 seconds
[2023-05-20T15:26:14.347+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:14.348+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:26:14.349+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:26:14.348+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:14.353+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:26:14.350+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:26:14.353+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:14.388+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.045 seconds
[2023-05-20T15:26:44.633+0000] {processor.py:153} INFO - Started process (PID=292) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:44.635+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:26:44.636+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:26:44.635+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:44.638+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:26:44.637+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:26:44.639+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:26:44.661+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.031 seconds
[2023-05-20T15:27:15.266+0000] {processor.py:153} INFO - Started process (PID=345) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:15.266+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:27:15.267+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:27:15.267+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:15.269+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:27:15.268+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:27:15.270+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:15.295+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.036 seconds
[2023-05-20T15:27:46.097+0000] {processor.py:153} INFO - Started process (PID=397) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:46.098+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:27:46.099+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:27:46.099+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:46.101+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:27:46.101+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:27:46.102+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:27:46.154+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.069 seconds
[2023-05-20T15:28:16.455+0000] {processor.py:153} INFO - Started process (PID=449) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:16.456+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:28:16.457+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:28:16.457+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:16.459+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:28:16.459+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:28:16.460+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:16.480+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:28:47.358+0000] {processor.py:153} INFO - Started process (PID=501) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:47.360+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:28:47.360+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:28:47.360+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:47.363+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:28:47.362+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:28:47.363+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:28:47.384+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:29:17.618+0000] {processor.py:153} INFO - Started process (PID=553) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:17.619+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:29:17.620+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:29:17.620+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:17.622+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:29:17.621+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:29:17.623+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:17.644+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:29:47.901+0000] {processor.py:153} INFO - Started process (PID=606) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:47.902+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:29:47.902+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:29:47.902+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:47.905+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:29:47.904+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:29:47.905+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:29:47.926+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:30:18.931+0000] {processor.py:153} INFO - Started process (PID=657) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:18.934+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:30:18.934+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:30:18.934+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:18.937+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:30:18.936+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:30:18.937+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:18.957+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:30:49.142+0000] {processor.py:153} INFO - Started process (PID=710) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:49.143+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:30:49.144+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:30:49.144+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:49.146+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:30:49.146+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:30:49.147+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:30:49.169+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:31:20.125+0000] {processor.py:153} INFO - Started process (PID=762) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:20.127+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:31:20.128+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:31:20.128+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:20.130+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:31:20.129+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:31:20.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:20.151+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:31:50.406+0000] {processor.py:153} INFO - Started process (PID=815) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:50.407+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:31:50.408+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:31:50.407+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:50.410+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:31:50.409+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:31:50.410+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:31:50.430+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:32:20.821+0000] {processor.py:153} INFO - Started process (PID=866) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:20.821+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:32:20.822+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:32:20.822+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:20.825+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:32:20.823+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:32:20.825+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:20.845+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:32:51.209+0000] {processor.py:153} INFO - Started process (PID=918) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:51.210+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:32:51.211+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:32:51.210+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:51.213+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:32:51.212+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:32:51.213+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:32:51.234+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:33:21.809+0000] {processor.py:153} INFO - Started process (PID=970) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:21.810+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:33:21.810+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:33:21.810+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:21.813+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:33:21.812+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:33:21.813+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:21.834+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.028 seconds
[2023-05-20T15:33:51.989+0000] {processor.py:153} INFO - Started process (PID=1023) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:51.990+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:33:51.991+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:33:51.991+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:51.994+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:33:51.993+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:33:51.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:33:52.016+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.031 seconds
[2023-05-20T15:34:22.070+0000] {processor.py:153} INFO - Started process (PID=1076) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:22.072+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:34:22.073+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:34:22.072+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:22.075+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:34:22.074+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:34:22.076+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:22.098+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.032 seconds
[2023-05-20T15:34:52.549+0000] {processor.py:153} INFO - Started process (PID=1128) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:52.550+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:34:52.551+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:34:52.550+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:52.553+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:34:52.552+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:34:52.554+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:34:52.576+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:35:22.617+0000] {processor.py:153} INFO - Started process (PID=1180) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:22.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:35:22.618+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:35:22.618+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:22.621+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:35:22.620+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:35:22.621+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:22.642+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:35:53.266+0000] {processor.py:153} INFO - Started process (PID=1232) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:53.267+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:35:53.267+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:35:53.267+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:53.270+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:35:53.269+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:35:53.270+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:35:53.292+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:36:23.391+0000] {processor.py:153} INFO - Started process (PID=1284) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:23.392+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:36:23.393+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:36:23.393+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:23.395+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:36:23.394+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:36:23.396+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:23.417+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:36:54.267+0000] {processor.py:153} INFO - Started process (PID=1336) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:54.268+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:36:54.269+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:36:54.268+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:54.271+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:36:54.270+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:36:54.271+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:36:54.293+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T15:37:25.176+0000] {processor.py:153} INFO - Started process (PID=1397) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:25.177+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:37:25.178+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:37:25.178+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:25.186+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:37:25.184+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:37:25.186+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:25.207+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.037 seconds
[2023-05-20T15:37:55.799+0000] {processor.py:153} INFO - Started process (PID=1449) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:55.800+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:37:55.800+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:37:55.800+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:55.803+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:37:55.802+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:37:55.803+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:37:55.824+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.029 seconds
[2023-05-20T15:38:26.436+0000] {processor.py:153} INFO - Started process (PID=1501) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:38:26.441+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T15:38:26.441+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:38:26.441+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:38:26.444+0000] {logging_mixin.py:137} INFO - [2023-05-20T15:38:26.443+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T15:38:26.444+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T15:38:26.485+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.053 seconds
[2023-05-20T16:20:06.079+0000] {processor.py:153} INFO - Started process (PID=33) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:06.105+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:20:06.106+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:20:06.106+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:06.126+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:20:06.110+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:20:06.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:06.218+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.142 seconds
[2023-05-20T16:20:36.973+0000] {processor.py:153} INFO - Started process (PID=85) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:36.974+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:20:36.975+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:20:36.975+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:36.977+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:20:36.976+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:20:36.978+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:20:37.000+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T16:21:07.095+0000] {processor.py:153} INFO - Started process (PID=137) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:07.096+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:21:07.097+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:21:07.097+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:07.100+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:21:07.099+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:21:07.100+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:07.133+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.044 seconds
[2023-05-20T16:21:37.222+0000] {processor.py:153} INFO - Started process (PID=189) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:37.223+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:21:37.224+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:21:37.224+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:37.226+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:21:37.225+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:21:37.227+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:21:37.249+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.030 seconds
[2023-05-20T16:22:07.592+0000] {processor.py:153} INFO - Started process (PID=241) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:07.594+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:22:07.594+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:22:07.594+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:07.597+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:22:07.596+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:22:07.597+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:07.620+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.031 seconds
[2023-05-20T16:22:38.031+0000] {processor.py:153} INFO - Started process (PID=293) to work on /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:38.037+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/todays_gamesv3.py for tasks to queue
[2023-05-20T16:22:38.038+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:22:38.038+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:38.041+0000] {logging_mixin.py:137} INFO - [2023-05-20T16:22:38.040+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/todays_gamesv3.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/todays_gamesv3.py", line 44
    dag=dag
      ^
SyntaxError: invalid syntax
[2023-05-20T16:22:38.041+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/todays_gamesv3.py
[2023-05-20T16:22:38.064+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/todays_gamesv3.py took 0.038 seconds
