[2023-05-21T21:34:22.017+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv3.call_standings_task manual__2023-05-21T21:34:12.196281+00:00 [queued]>
[2023-05-21T21:34:22.028+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv3.call_standings_task manual__2023-05-21T21:34:12.196281+00:00 [queued]>
[2023-05-21T21:34:22.029+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T21:34:22.029+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-05-21T21:34:22.029+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-05-21T21:34:22.047+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): call_standings_task> on 2023-05-21 21:34:12.196281+00:00
[2023-05-21T21:34:22.060+0000] {standard_task_runner.py:55} INFO - Started process 565 to run task
[2023-05-21T21:34:22.073+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv3', 'call_standings_task', 'manual__2023-05-21T21:34:12.196281+00:00', '--job-id', '176', '--raw', '--subdir', 'DAGS_FOLDER/todays_gamesv3.py', '--cfg-path', '/tmp/tmp54s281pg']
[2023-05-21T21:34:22.073+0000] {standard_task_runner.py:83} INFO - Job 176: Subtask call_standings_task
[2023-05-21T21:34:22.205+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv3.call_standings_task manual__2023-05-21T21:34:12.196281+00:00 [running]> on host b03c83f459ca
[2023-05-21T21:34:22.359+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv3
AIRFLOW_CTX_TASK_ID=call_standings_task
AIRFLOW_CTX_EXECUTION_DATE=2023-05-21T21:34:12.196281+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-21T21:34:12.196281+00:00
[2023-05-21T21:34:22.375+0000] {logging_mixin.py:137} INFO - {'0': {'game_id': 718085, 'game_datetime': '2023-05-21T15:35:00Z', 'game_date': '2023-05-21', 'game_type': 'R', 'status': 'Final', 'away_name': 'New York Yankees', 'home_name': 'Cincinnati Reds', 'away_id': 147, 'home_id': 113, 'doubleheader': 'N', 'game_num': 1, 'home_probable_pitcher': 'Hunter Greene', 'away_probable_pitcher': 'Luis Severino', 'home_pitcher_note': '', 'away_pitcher_note': '', 'away_score': 4, 'home_score': 1, 'current_inning': 9, 'inning_state': 'Bottom', 'venue_id': 2602, 'venue_name': 'Great American Ball Park', 'national_broadcasts': ['Peacock'], 'series_status': 'NYY wins 3-0', 'winning_team': 'New York Yankees', 'losing_team': 'Cincinnati Reds', 'winning_pitcher': 'Albert Abreu', 'losing_pitcher': 'Hunter Greene', 'save_pitcher': 'Clay Holmes', 'summary': '2023-05-21 - New York Yankees (4) @ Cincinnati Reds (1) (Final)', 'game_time': '11:35 PM'}}
[2023-05-21T21:34:22.377+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/functions/_call_standings.py", line 9, in _call_standings
    standings = standings_data()
NameError: name 'standings_data' is not defined
[2023-05-21T21:34:22.387+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv3, task_id=call_standings_task, execution_date=20230521T213412, start_date=20230521T213422, end_date=20230521T213422
[2023-05-21T21:34:22.409+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 176 for task call_standings_task (name 'standings_data' is not defined; 565)
[2023-05-21T21:34:22.446+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-05-21T21:34:22.519+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
