[2023-04-03T02:19:45.849+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_sql_table_task manual__2023-04-03T02:19:34.428936+00:00 [queued]>
[2023-04-03T02:19:45.879+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: get_todays_gamesv4.write_sql_table_task manual__2023-04-03T02:19:34.428936+00:00 [queued]>
[2023-04-03T02:19:45.879+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:19:45.879+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 1
[2023-04-03T02:19:45.879+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-04-03T02:19:45.922+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_sql_table_task> on 2023-04-03 02:19:34.428936+00:00
[2023-04-03T02:19:45.941+0000] {standard_task_runner.py:55} INFO - Started process 985 to run task
[2023-04-03T02:19:45.957+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'get_todays_gamesv4', 'write_sql_table_task', 'manual__2023-04-03T02:19:34.428936+00:00', '--job-id', '118', '--raw', '--subdir', 'DAGS_FOLDER/todays_games.py', '--cfg-path', '/tmp/tmprue0qi52']
[2023-04-03T02:19:45.958+0000] {standard_task_runner.py:83} INFO - Job 118: Subtask write_sql_table_task
[2023-04-03T02:19:46.157+0000] {task_command.py:388} INFO - Running <TaskInstance: get_todays_gamesv4.write_sql_table_task manual__2023-04-03T02:19:34.428936+00:00 [running]> on host bb4d827b1601
[2023-04-03T02:19:46.337+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=get_todays_gamesv4
AIRFLOW_CTX_TASK_ID=write_sql_table_task
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T02:19:34.428936+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-03T02:19:34.428936+00:00
[2023-04-03T02:19:46.356+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/todays_games.py", line 44, in _write_sql_table
    for k,v in games.items():
AttributeError: 'NoneType' object has no attribute 'items'
[2023-04-03T02:19:46.367+0000] {taskinstance.py:1326} INFO - Marking task as FAILED. dag_id=get_todays_gamesv4, task_id=write_sql_table_task, execution_date=20230403T021934, start_date=20230403T021945, end_date=20230403T021946
[2023-04-03T02:19:46.389+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 118 for task write_sql_table_task ('NoneType' object has no attribute 'items'; 985)
[2023-04-03T02:19:46.432+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-03T02:19:46.490+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
